using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyDescription("IP phone. All rights reserved.")]
[assembly: AssemblyCompany("http://www.contactpoint.com.ua/")]
[assembly: AssemblyProduct("IP phone")]
[assembly: AssemblyCopyright("Copyright © ContactPoint")]
[assembly: AssemblyTrademark("ContactPoint")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.99.9999.9999")]

