//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactPoint.CaptionStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CaptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactPoint.CaptionStrings.CaptionStrings", typeof(CaptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста подождите.
        /// </summary>
        internal static string ActionTransferDescription {
            get {
                return ResourceManager.GetString("ActionTransferDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансфер на номер {0}.
        /// </summary>
        internal static string ActionTransferTitle {
            get {
                return ResourceManager.GetString("ActionTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to воспроизведение.
        /// </summary>
        internal static string AudioDevicePlayback {
            get {
                return ResourceManager.GetString("AudioDevicePlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to запись.
        /// </summary>
        internal static string AudioDeviceRecording {
            get {
                return ResourceManager.GetString("AudioDeviceRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет устройства.
        /// </summary>
        internal static string AudioDeviceUnknown {
            get {
                return ResourceManager.GetString("AudioDeviceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP PHONE.
        /// </summary>
        internal static string BaseTitle {
            get {
                return ResourceManager.GetString("BaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to стереть.
        /// </summary>
        internal static string ButtonBackspace {
            get {
                return ResourceManager.GetString("ButtonBackspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to конф.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удерж.
        /// </summary>
        internal static string ButtonHold {
            get {
                return ResourceManager.GetString("ButtonHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to трансф.
        /// </summary>
        internal static string ButtonTransfer {
            get {
                return ResourceManager.GetString("ButtonTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите закрыть программу?.
        /// </summary>
        internal static string CloseQuestion {
            get {
                return ResourceManager.GetString("CloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружены новые устройства.
        /// </summary>
        internal static string DevicesAdded {
            get {
                return ResourceManager.GetString("DevicesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройства извлечены из системы.
        /// </summary>
        internal static string DevicesRemoved {
            get {
                return ResourceManager.GetString("DevicesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите попытку немного позже.
        /// </summary>
        internal static string ErrorBusyDescription {
            get {
                return ResourceManager.GetString("ErrorBusyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер занят.
        /// </summary>
        internal static string ErrorBusyTitle {
            get {
                return ResourceManager.GetString("ErrorBusyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможно не введена информация о сервере или введена некорректно.
        /// </summary>
        internal static string ErrorDisconnectedDescription {
            get {
                return ResourceManager.GetString("ErrorDisconnectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP аккаунт не подключен.
        /// </summary>
        internal static string ErrorDisconnectedTitle {
            get {
                return ResourceManager.GetString("ErrorDisconnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбраны аудио устройства.
        /// </summary>
        internal static string ErrorNoAudioDevices {
            get {
                return ResourceManager.GetString("ErrorNoAudioDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможно нет свободных линий.
        /// </summary>
        internal static string ErrorNoAvailableLinesDescription {
            get {
                return ResourceManager.GetString("ErrorNoAvailableLinesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звонок не удался!.
        /// </summary>
        internal static string ErrorNoAvailableLinesTitle {
            get {
                return ResourceManager.GetString("ErrorNoAvailableLinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбраны динамики.
        /// </summary>
        internal static string ErrorNoPlaybackDevice {
            get {
                return ResourceManager.GetString("ErrorNoPlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран микрофон.
        /// </summary>
        internal static string ErrorNoRecordingDevice {
            get {
                return ResourceManager.GetString("ErrorNoRecordingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте правильность ввода номер и попробуйте еще раз.
        /// </summary>
        internal static string ErrorWrongNumberDescription {
            get {
                return ResourceManager.GetString("ErrorWrongNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправльный номер или абонент недоступен.
        /// </summary>
        internal static string ErrorWrongNumberTitle {
            get {
                return ResourceManager.GetString("ErrorWrongNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть....
        /// </summary>
        internal static string MenuItemClose {
            get {
                return ResourceManager.GetString("MenuItemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки....
        /// </summary>
        internal static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        internal static string MenuItemShow {
            get {
                return ResourceManager.GetString("MenuItemShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поверх всех окон.
        /// </summary>
        internal static string MenuItemTopMost {
            get {
                return ResourceManager.GetString("MenuItemTopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение! Не выбран ни один кодек.
        /// </summary>
        internal static string NoCodecsSelected {
            get {
                return ResourceManager.GetString("NoCodecsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство воспроизведения изменено.
        /// </summary>
        internal static string PlaybackDeviceChanged {
            get {
                return ResourceManager.GetString("PlaybackDeviceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство записи изменено.
        /// </summary>
        internal static string RecordingDeviceChanged {
            get {
                return ResourceManager.GetString("RecordingDeviceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходим перезапуск программы.
        /// </summary>
        internal static string RestartNeeded {
            get {
                return ResourceManager.GetString("RestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to открыть настройки.
        /// </summary>
        internal static string ShowAudioDevicesSettings {
            get {
                return ResourceManager.GetString("ShowAudioDevicesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение....
        /// </summary>
        internal static string StateConnecting {
            get {
                return ResourceManager.GetString("StateConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключен.
        /// </summary>
        internal static string StateDisconnected {
            get {
                return ResourceManager.GetString("StateDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инициализация....
        /// </summary>
        internal static string StateInitializing {
            get {
                return ResourceManager.GetString("StateInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звонок.
        /// </summary>
        internal static string StateOnThePhone {
            get {
                return ResourceManager.GetString("StateOnThePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пауза.
        /// </summary>
        internal static string StatePause {
            get {
                return ResourceManager.GetString("StatePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готов.
        /// </summary>
        internal static string StateReady {
            get {
                return ResourceManager.GetString("StateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать.
        /// </summary>
        internal static string UseDevice {
            get {
                return ResourceManager.GetString("UseDevice", resourceCulture);
            }
        }
    }
}
